---
- name: copy .gemrc into ~
  copy:
    src: gemrc
    dest: ~/.gemrc

- name: install/update ruby tooling
  homebrew: name={{ item }} state=latest
  with_items:
    - rbenv
    - rbenv-bundle-exec
    - rbenv-default-gems
    - rbenv-gem-rehash
    - rbenv-vars
    - ruby-build

- name: ensure ~/.rbenv directory exists
  file: path=~/.rbenv state=directory

- name: add ruby configuration to zsh
  copy: src=ruby.zsh dest={{ zshrc_d }}
